//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juego_Hotel.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mensajes_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mensajes_en() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juego_Hotel.Resources.mensajes_en", typeof(mensajes_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current game will be lost if you continue, whether the load is successful or not, will you proceed?.
        /// </summary>
        internal static string mensajeCargarPartida {
            get {
                return ResourceManager.GetString("mensajeCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have fallen into a free input type square,advantage!.
        /// </summary>
        internal static string mensajeCasillaEntradaGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have fallen into a phase free type square, advantage!.
        /// </summary>
        internal static string mensajeCasillaFaseGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can buy the hotel. If you decide to continue, you are obliged to pay\nDo you want to purchase?.
        /// </summary>
        internal static string mensajeComprarHotel {
            get {
                return ResourceManager.GetString("mensajeComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player {0} must pay night to player {1}. Click OK to roll the dice..
        /// </summary>
        internal static string mensajeDebePagarNoches {
            get {
                return ResourceManager.GetString("mensajeDebePagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading the game: {0}.
        /// </summary>
        internal static string mensajeErrorAlCargar {
            get {
                return ResourceManager.GetString("mensajeErrorAlCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving the game: {0}.
        /// </summary>
        internal static string mensajeErrorAlSalvar {
            get {
                return ResourceManager.GetString("mensajeErrorAlSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to load the configuration file Config.xml.
        /// </summary>
        internal static string mensajeErrorCargarConfig {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to load the configuration from the server.
        /// </summary>
        internal static string mensajeErrorCargarConfigServidor {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfigServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The hotel already has an owner and is not expropriate.
        /// </summary>
        internal static string mensajeExpropiacionImposible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to expropriate the hotel {0} to the player {1}?.
        /// </summary>
        internal static string mensajeExpropiacionPosible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have sufficient funds for the purchase of the hotel {0}.
        /// </summary>
        internal static string mensajeFondosInsuficientesParaComprarHotel {
            get {
                return ResourceManager.GetString("mensajeFondosInsuficientesParaComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already own this hotel.
        /// </summary>
        internal static string mensajeImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("mensajeImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game ends because all players have folded.
        /// </summary>
        internal static string mensajeJugadoresRetidados {
            get {
                return ResourceManager.GetString("mensajeJugadoresRetidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not been indicated even the number of players.
        /// </summary>
        internal static string mensajeNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have any hotels.
        /// </summary>
        internal static string mensajeNoPoseesHoteles {
            get {
                return ResourceManager.GetString("mensajeNoPoseesHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game ends. He won the Player {0}.
        /// </summary>
        internal static string mensajePartidaFinalizada {
            get {
                return ResourceManager.GetString("mensajePartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to restart the game?.
        /// </summary>
        internal static string mensajeReiniciarPartida {
            get {
                return ResourceManager.GetString("mensajeReiniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to retire?.
        /// </summary>
        internal static string mensajeRetirarse {
            get {
                return ResourceManager.GetString("mensajeRetirarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You get a 6. You can re-roll.
        /// </summary>
        internal static string mensajeSacadoUnSeis {
            get {
                return ResourceManager.GetString("mensajeSacadoUnSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can only save before throwing the dice.
        /// </summary>
        internal static string mensajeSalvarAntesDeTirar {
            get {
                return ResourceManager.GetString("mensajeSalvarAntesDeTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the number of players.
        /// </summary>
        internal static string mensajeSelecJugadores {
            get {
                return ResourceManager.GetString("mensajeSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have sufficient funds to carry out the expropriation.
        /// </summary>
        internal static string mensajeSinFondosParaExpropiacion {
            get {
                return ResourceManager.GetString("mensajeSinFondosParaExpropiacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You get a {0}, so the player {1} must pay {2} to player {3}.
        /// </summary>
        internal static string mensajeTotalAPagar {
            get {
                return ResourceManager.GetString("mensajeTotalAPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load game.
        /// </summary>
        internal static string tituloCargarPartida {
            get {
                return ResourceManager.GetString("tituloCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy hotel.
        /// </summary>
        internal static string tituloComprarHotel {
            get {
                return ResourceManager.GetString("tituloComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load a game.
        /// </summary>
        internal static string tituloDialogoCargarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save current game.
        /// </summary>
        internal static string tituloDialogoGuardarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string tituloError {
            get {
                return ResourceManager.GetString("tituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriation impossible.
        /// </summary>
        internal static string tituloExpropiacionImposible {
            get {
                return ResourceManager.GetString("tituloExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriation possible.
        /// </summary>
        internal static string tituloExpropiacionPosible {
            get {
                return ResourceManager.GetString("tituloExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel.
        /// </summary>
        internal static string tituloHotel {
            get {
                return ResourceManager.GetString("tituloHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not buy.
        /// </summary>
        internal static string tituloImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("tituloImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to show your hotels.
        /// </summary>
        internal static string tituloNoEsPosibleMostrarTusHoteles {
            get {
                return ResourceManager.GetString("tituloNoEsPosibleMostrarTusHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not possible to put entrances.
        /// </summary>
        internal static string tituloNoesPosiblePonerEntradas {
            get {
                return ResourceManager.GetString("tituloNoesPosiblePonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection of colors.
        /// </summary>
        internal static string tituloNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("tituloNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay nights.
        /// </summary>
        internal static string tituloPagarNoches {
            get {
                return ResourceManager.GetString("tituloPagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to Start.
        /// </summary>
        internal static string tituloSelecJugadores {
            get {
                return ResourceManager.GetString("tituloSelecJugadores", resourceCulture);
            }
        }
    }
}
