//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juego_Hotel.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juego_Hotel.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string comboBoxIdiomas1 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string comboBoxIdiomas2 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida de Hotel|*.xml.
        /// </summary>
        internal static string filtroDialogoCargarGuardarPartida {
            get {
                return ResourceManager.GetString("filtroDialogoCargarGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres comprobar si existe una versión del juego más actualizada?.
        /// </summary>
        internal static string mensajeActualizar {
            get {
                return ResourceManager.GetString("mensajeActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida actual se perderá si continúas, tanto si la carga es exitosa como no, ¿Quieres proceder?.
        /// </summary>
        internal static string mensajeCargarPartida {
            get {
                return ResourceManager.GetString("mensajeCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Entrada Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaEntradaGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Fase Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaFaseGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes comprar el hotel. Si decides continuar, estás obligado a pagarlo. ¿Deseas realizar la compra?.
        /// </summary>
        internal static string mensajeComprarHotel {
            get {
                return ResourceManager.GetString("mensajeComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} debe pagar las noches al jugador {1}. Pulsa OK para lanzar el dado..
        /// </summary>
        internal static string mensajeDebePagarNoches {
            get {
                return ResourceManager.GetString("mensajeDebePagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error comprobando la versión. Ve a https://sourceforge.net/projects/hotels-game/ para comprobar la versión manualmente..
        /// </summary>
        internal static string mensajeErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlCargar {
            get {
                return ResourceManager.GetString("mensajeErrorAlCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error salvando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlSalvar {
            get {
                return ResourceManager.GetString("mensajeErrorAlSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar el fichero de configuración Config.xml.
        /// </summary>
        internal static string mensajeErrorCargarConfig {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar la configuración desde el servidor.
        /// </summary>
        internal static string mensajeErrorCargarConfigServidor {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfigServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel ya tiene dueño y no es expropiable.
        /// </summary>
        internal static string mensajeExpropiacionImposible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres expropiar el hotel {0} al jugador {1}?.
        /// </summary>
        internal static string mensajeExpropiacionPosible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la compra del hotel {0}.
        /// </summary>
        internal static string mensajeFondosInsuficientesParaComprarHotel {
            get {
                return ResourceManager.GetString("mensajeFondosInsuficientesParaComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya posees este hotel.
        /// </summary>
        internal static string mensajeImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("mensajeImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada porque todos los jugadores se han retirado.
        /// </summary>
        internal static string mensajeJugadoresRetidados {
            get {
                return ResourceManager.GetString("mensajeJugadoresRetidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El error producido fue:.
        /// </summary>
        internal static string mensajeMostrarErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeMostrarErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha indicado aun el número de jugadores.
        /// </summary>
        internal static string mensajeNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una versión más nueva :).
        /// </summary>
        internal static string mensajeNoNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNoNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posees ningún hotel.
        /// </summary>
        internal static string mensajeNoPoseesHoteles {
            get {
                return ResourceManager.GetString("mensajeNoPoseesHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una versión diferente ({0}) que la que estás usando ({1}). ¿Quieres acceder a la página del proyecto en SourceForge? El juego se cerrará..
        /// </summary>
        internal static string mensajeNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada. ¡Ha ganado el jugador {0}!.
        /// </summary>
        internal static string mensajePartidaFinalizada {
            get {
                return ResourceManager.GetString("mensajePartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres jugar online?.
        /// </summary>
        internal static string mensajePreguntarSiOnline {
            get {
                return ResourceManager.GetString("mensajePreguntarSiOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres reiniciar la partida?.
        /// </summary>
        internal static string mensajeReiniciarPartida {
            get {
                return ResourceManager.GetString("mensajeReiniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres retirarte?.
        /// </summary>
        internal static string mensajeRetirarse {
            get {
                return ResourceManager.GetString("mensajeRetirarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Has sacado un 6. Puedes volver a tirar!.
        /// </summary>
        internal static string mensajeSacadoUnSeis {
            get {
                return ResourceManager.GetString("mensajeSacadoUnSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se puede salvar antes de tirar el dado.
        /// </summary>
        internal static string mensajeSalvarAntesDeTirar {
            get {
                return ResourceManager.GetString("mensajeSalvarAntesDeTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el nº de jugadores.
        /// </summary>
        internal static string mensajeSelecJugadores {
            get {
                return ResourceManager.GetString("mensajeSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la expropiación.
        /// </summary>
        internal static string mensajeSinFondosParaExpropiacion {
            get {
                return ResourceManager.GetString("mensajeSinFondosParaExpropiacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sacado un {0}, por lo que el jugador {1} debe abonar {2} al jugador {3}.
        /// </summary>
        internal static string mensajeTotalAPagar {
            get {
                return ResourceManager.GetString("mensajeTotalAPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a Hotel!.
        /// </summary>
        internal static string tituloBienvenido {
            get {
                return ResourceManager.GetString("tituloBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Partida.
        /// </summary>
        internal static string tituloCargarPartida {
            get {
                return ResourceManager.GetString("tituloCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar hotel.
        /// </summary>
        internal static string tituloComprarHotel {
            get {
                return ResourceManager.GetString("tituloComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar una partida.
        /// </summary>
        internal static string tituloDialogoCargarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar una partida.
        /// </summary>
        internal static string tituloDialogoGuardarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string tituloError {
            get {
                return ResourceManager.GetString("tituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación imposible.
        /// </summary>
        internal static string tituloExpropiacionImposible {
            get {
                return ResourceManager.GetString("tituloExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación posible.
        /// </summary>
        internal static string tituloExpropiacionPosible {
            get {
                return ResourceManager.GetString("tituloExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotels.
        /// </summary>
        internal static string tituloHotel {
            get {
                return ResourceManager.GetString("tituloHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible realizar la compra.
        /// </summary>
        internal static string tituloImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("tituloImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible mostrar tus hoteles.
        /// </summary>
        internal static string tituloNoEsPosibleMostrarTusHoteles {
            get {
                return ResourceManager.GetString("tituloNoEsPosibleMostrarTusHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible poner entradas.
        /// </summary>
        internal static string tituloNoesPosiblePonerEntradas {
            get {
                return ResourceManager.GetString("tituloNoesPosiblePonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de colores.
        /// </summary>
        internal static string tituloNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("tituloNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar noches.
        /// </summary>
        internal static string tituloPagarNoches {
            get {
                return ResourceManager.GetString("tituloPagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible iniciar.
        /// </summary>
        internal static string tituloSelecJugadores {
            get {
                return ResourceManager.GetString("tituloSelecJugadores", resourceCulture);
            }
        }
    }
}
