//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juego_Hotel.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juego_Hotel.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amarillo.
        /// </summary>
        internal static string colorAmarillo {
            get {
                return ResourceManager.GetString("colorAmarillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a azul.
        /// </summary>
        internal static string colorAzul {
            get {
                return ResourceManager.GetString("colorAzul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rojo.
        /// </summary>
        internal static string colorRojo {
            get {
                return ResourceManager.GetString("colorRojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a verde.
        /// </summary>
        internal static string colorVerde {
            get {
                return ResourceManager.GetString("colorVerde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string comboBoxIdiomas1 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string comboBoxIdiomas2 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida de Hotel|*.xml.
        /// </summary>
        internal static string filtroDialogoCargarGuardarPartida {
            get {
                return ResourceManager.GetString("filtroDialogoCargarGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha comprado el hotel {2}..
        /// </summary>
        internal static string MAComprarHotel {
            get {
                return ResourceManager.GetString("MAComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha tirado el dado y ha sacado un {2}..
        /// </summary>
        internal static string MADadoTirado {
            get {
                return ResourceManager.GetString("MADadoTirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) está ausente. Dado tirado automáticamente con resultado: {2}.
        /// </summary>
        internal static string MADadoTiradoAuto {
            get {
                return ResourceManager.GetString("MADadoTiradoAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha añadido una entrada (en la posición {2}) al hotel {3}..
        /// </summary>
        internal static string MAEntradaAñadida {
            get {
                return ResourceManager.GetString("MAEntradaAñadida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha expropiado al jugador {2} ({3}) el hotel {4}..
        /// </summary>
        internal static string MAExpropiarHotel {
            get {
                return ResourceManager.GetString("MAExpropiarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha intentado expropiar al jugador {2} ({3}) el hotel {4}, pero no ha podido..
        /// </summary>
        internal static string MAExpropiarHotelIntento {
            get {
                return ResourceManager.GetString("MAExpropiarHotelIntento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha añadido una fase (la número {2}) al hotel {3}..
        /// </summary>
        internal static string MAFaseAñadida {
            get {
                return ResourceManager.GetString("MAFaseAñadida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha iniciado la subasta por el hotel {2}..
        /// </summary>
        internal static string MAIniciarSubasta {
            get {
                return ResourceManager.GetString("MAIniciarSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ofrece {2} por el hotel {3}..
        /// </summary>
        internal static string MANuevaPuja {
            get {
                return ResourceManager.GetString("MANuevaPuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha pasado el turno..
        /// </summary>
        internal static string MAPasarTurno {
            get {
                return ResourceManager.GetString("MAPasarTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) está ausente y se le ha pasado el turno automáticamente..
        /// </summary>
        internal static string MAPasarTurnoAuto {
            get {
                return ResourceManager.GetString("MAPasarTurnoAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) pide al jugador {2} ({3}) que pague {4} por {5} noches en el hotel {6}..
        /// </summary>
        internal static string MAPedirNochesOnline {
            get {
                return ResourceManager.GetString("MAPedirNochesOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha vendido el hotel {2} al jugador {3} ({4}) por una cantidad de {5}..
        /// </summary>
        internal static string MASubastaTerminada {
            get {
                return ResourceManager.GetString("MASubastaTerminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha vendido de forma automatica por inactividad el hotel {2} al jugador {3} ({4}) por una cantidad de {5}..
        /// </summary>
        internal static string MASubastaTerminadaAuto {
            get {
                return ResourceManager.GetString("MASubastaTerminadaAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha tirado el dado de construcción y ha sacado un {2}..
        /// </summary>
        internal static string MATirarDadoConstruccion {
            get {
                return ResourceManager.GetString("MATirarDadoConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El jugador {0} ({1}) ha tirado el dado de construcción y puede construir pero con coste doble!.
        /// </summary>
        internal static string MATirarDadoConstruccionDobleCoste {
            get {
                return ResourceManager.GetString("MATirarDadoConstruccionDobleCoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El jugador {0} ({1}) ha tirado el dado de construcción y puede construir gratis!.
        /// </summary>
        internal static string MATirarDadoConstruccionGratis {
            get {
                return ResourceManager.GetString("MATirarDadoConstruccionGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El jugador {0} ({1}) ha tirado el dado de construcción pero no se le permite construir!.
        /// </summary>
        internal static string MATirarDadoConstruccionKo {
            get {
                return ResourceManager.GetString("MATirarDadoConstruccionKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El jugador {0} ({1}) ha tirado el dado de construcción y se le permite construir!.
        /// </summary>
        internal static string MATirarDadoConstruccionOk {
            get {
                return ResourceManager.GetString("MATirarDadoConstruccionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres comprobar si existe una versión del juego más actualizada?.
        /// </summary>
        internal static string mensajeActualizar {
            get {
                return ResourceManager.GetString("mensajeActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apodo no puede superar 20 caracteres.
        /// </summary>
        internal static string mensajeApodoDemasiadoLargo {
            get {
                return ResourceManager.GetString("mensajeApodoDemasiadoLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apodo ya está en uso.
        /// </summary>
        internal static string mensajeApodoEnUso {
            get {
                return ResourceManager.GetString("mensajeApodoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apodo no puede estar vacío.
        /// </summary>
        internal static string mensajeApodoVacio {
            get {
                return ResourceManager.GetString("mensajeApodoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida actual se perderá si continúas, tanto si la carga es exitosa como no, ¿Quieres proceder?.
        /// </summary>
        internal static string mensajeCargarPartida {
            get {
                return ResourceManager.GetString("mensajeCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida cargada correctamente.
        /// </summary>
        internal static string mensajeCargarPartidaOK {
            get {
                return ResourceManager.GetString("mensajeCargarPartidaOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Entrada Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaEntradaGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Fase Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaFaseGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casilla está ocupada y no puedes añadir una entrada ahora mismo en ella.
        /// </summary>
        internal static string mensajeCasillaOcupada {
            get {
                return ResourceManager.GetString("mensajeCasillaOcupada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casilla ya tiene una entrada comprada para el hotel .
        /// </summary>
        internal static string mensajeCasillaYaPoseeEntrada {
            get {
                return ResourceManager.GetString("mensajeCasillaYaPoseeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres que se cierre cualquier chat abierto?.
        /// </summary>
        internal static string mensajeCerrarChatsAbiertos {
            get {
                return ResourceManager.GetString("mensajeCerrarChatsAbiertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres que se cierre cualquier partida abierta?.
        /// </summary>
        internal static string mensajeCerrarPartidasAbiertas {
            get {
                return ResourceManager.GetString("mensajeCerrarPartidasAbiertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comando desconocido: .
        /// </summary>
        internal static string mensajeComandoDesconocido {
            get {
                return ResourceManager.GetString("mensajeComandoDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si aceptas comprar la entrada, estás obligado a pagarla. ¿Deseas realizar la compra?.
        /// </summary>
        internal static string mensajeComprarEntradas {
            get {
                return ResourceManager.GetString("mensajeComprarEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes comprar el hotel. Si decides continuar, estás obligado a pagarlo. ¿Deseas realizar la compra?.
        /// </summary>
        internal static string mensajeComprarHotel {
            get {
                return ResourceManager.GetString("mensajeComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres subastar el hotel?
        ///Esta operación no se puede cancelar.
        /// </summary>
        internal static string mensajeConfirmacionSubasta {
            get {
                return ResourceManager.GetString("mensajeConfirmacionSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres realizar la puja? No puede deshacerse.
        /// </summary>
        internal static string mensajeConfirmarPuja {
            get {
                return ResourceManager.GetString("mensajeConfirmarPuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres realizar la venta final? No puede deshacerse
        ///El jugador {0} deberá abonar {1}.
        /// </summary>
        internal static string mensajeConfirmarVentaSubasta {
            get {
                return ResourceManager.GetString("mensajeConfirmarVentaSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción denegada.
        /// </summary>
        internal static string mensajeConstruccionDenegada {
            get {
                return ResourceManager.GetString("mensajeConstruccionDenegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción de coste doble.
        /// </summary>
        internal static string mensajeConstruccionDobleCoste {
            get {
                return ResourceManager.GetString("mensajeConstruccionDobleCoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción gratuita.
        /// </summary>
        internal static string mensajeConstruccionGratuita {
            get {
                return ResourceManager.GetString("mensajeConstruccionGratuita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción permitida.
        /// </summary>
        internal static string mensajeConstruccionPermitida {
            get {
                return ResourceManager.GetString("mensajeConstruccionPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a construidas: .
        /// </summary>
        internal static string mensajeConstruidas {
            get {
                return ResourceManager.GetString("mensajeConstruidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos incorrectos: .
        /// </summary>
        internal static string mensajeDatosIncorrectos {
            get {
                return ResourceManager.GetString("mensajeDatosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} debe pagar las noches al jugador {1}. Pulsa OK para lanzar el dado..
        /// </summary>
        internal static string mensajeDebePagarNoches {
            get {
                return ResourceManager.GetString("mensajeDebePagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dueño: .
        /// </summary>
        internal static string mensajeDuenio {
            get {
                return ResourceManager.GetString("mensajeDuenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error comprobando la versión. Ve a https://sourceforge.net/projects/hotels-game/ para comprobar la versión manualmente..
        /// </summary>
        internal static string mensajeErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error actualizando lista de jugadores: .
        /// </summary>
        internal static string mensajeErrorActualizandoListaJugadores {
            get {
                return ResourceManager.GetString("mensajeErrorActualizandoListaJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlCargar {
            get {
                return ResourceManager.GetString("mensajeErrorAlCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error comprobando la versión. Ve a {0} para comprobar la versión manualmente..
        /// </summary>
        internal static string mensajeErrorAlComprobarVersion {
            get {
                return ResourceManager.GetString("mensajeErrorAlComprobarVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error salvando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlSalvar {
            get {
                return ResourceManager.GetString("mensajeErrorAlSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, rellena el campo email.
        /// </summary>
        internal static string mensajeErrorBugReportEmailVacio {
            get {
                return ResourceManager.GetString("mensajeErrorBugReportEmailVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ¡escribe algo como contenido!.
        /// </summary>
        internal static string mensajeErrorBugReportTextoVacio {
            get {
                return ResourceManager.GetString("mensajeErrorBugReportTextoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El fichero de la partida ha sido modificado incorrectamente: El hotel {0} tiene unas entradas asignadas que no pertenecen al hotel.
        /// </summary>
        internal static string mensajeErrorCarcarHotelConEntradasErroneas {
            get {
                return ResourceManager.GetString("mensajeErrorCarcarHotelConEntradasErroneas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar el fichero de configuración Config.xml.
        /// </summary>
        internal static string mensajeErrorCargarConfig {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar la configuración desde el servidor.
        /// </summary>
        internal static string mensajeErrorCargarConfigServidor {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfigServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel {0} tiene más fases construidas que el número máximo de fases.
        /// </summary>
        internal static string mensajeErrorCargarHotelConMasFases {
            get {
                return ResourceManager.GetString("mensajeErrorCargarHotelConMasFases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida no contiene datos de todos los jugadores.
        /// </summary>
        internal static string mensajeErrorCargarPartidaSinDatosJugadores {
            get {
                return ResourceManager.GetString("mensajeErrorCargarPartidaSinDatosJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conectando: .
        /// </summary>
        internal static string mensajeErrorConectando {
            get {
                return ResourceManager.GetString("mensajeErrorConectando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión: .
        /// </summary>
        internal static string mensajeErrorConexion {
            get {
                return ResourceManager.GetString("mensajeErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al desconectar: .
        /// </summary>
        internal static string mensajeErrorDesconectar {
            get {
                return ResourceManager.GetString("mensajeErrorDesconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error haciendo login: .
        /// </summary>
        internal static string mensajeErrorLogin {
            get {
                return ResourceManager.GetString("mensajeErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo lista de partidas: .
        /// </summary>
        internal static string mensajeErrorObteniendoListaPartidas {
            get {
                return ResourceManager.GetString("mensajeErrorObteniendoListaPartidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo lista de usuarios: .
        /// </summary>
        internal static string mensajeErrorObteniendoListaUsuarios {
            get {
                return ResourceManager.GetString("mensajeErrorObteniendoListaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El puerto especificado es demasiado alto.
        /// </summary>
        internal static string mensajeErrorPuertoAlto {
            get {
                return ResourceManager.GetString("mensajeErrorPuertoAlto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El puerto especificado es demasiado bajo.
        /// </summary>
        internal static string mensajeErrorPuertoBajo {
            get {
                return ResourceManager.GetString("mensajeErrorPuertoBajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El puerto especificado no es numérico.
        /// </summary>
        internal static string mensajeErrorPuertoNoNumerico {
            get {
                return ResourceManager.GetString("mensajeErrorPuertoNoNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha introducido una cantidad válida.
        /// </summary>
        internal static string mensajeErrorPujaCantidadInvalida {
            get {
                return ResourceManager.GetString("mensajeErrorPujaCantidadInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad es menor o igual que la puja máxima.
        /// </summary>
        internal static string mensajeErrorPujaMenorMax {
            get {
                return ResourceManager.GetString("mensajeErrorPujaMenorMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad no es múltiplo de 50.
        /// </summary>
        internal static string mensajeErrorPujaNoMultiplo50 {
            get {
                return ResourceManager.GetString("mensajeErrorPujaNoMultiplo50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden introducir cantidades negativas.
        /// </summary>
        internal static string mensajeErrorPujaNoNegativo {
            get {
                return ResourceManager.GetString("mensajeErrorPujaNoNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha introducido un número entero.
        /// </summary>
        internal static string mensajeErrorPujaNoNumEntero {
            get {
                return ResourceManager.GetString("mensajeErrorPujaNoNumEntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad no supera el precio mínimo ({0}).
        /// </summary>
        internal static string mensajeErrorPujaNoPrecioMinimo {
            get {
                return ResourceManager.GetString("mensajeErrorPujaNoPrecioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad es mayor que el dinero total del jugador .
        /// </summary>
        internal static string mensajeErrorPujaNoSuficienteDinero {
            get {
                return ResourceManager.GetString("mensajeErrorPujaNoSuficienteDinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error recibiendo nuevo mensaje de chat: .
        /// </summary>
        internal static string mensajeErrorRecibiendoChat {
            get {
                return ResourceManager.GetString("mensajeErrorRecibiendoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error recibiendo nuevo mensaje de chat global: .
        /// </summary>
        internal static string mensajeErrorRecibiendoChatGlobal {
            get {
                return ResourceManager.GetString("mensajeErrorRecibiendoChatGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al salvar el idioma en Config.xml.
        /// </summary>
        internal static string mensajeErrorSalvandoIdioma {
            get {
                return ResourceManager.GetString("mensajeErrorSalvandoIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apodo excede la longitud máxima.
        /// </summary>
        internal static string mensajeErrorTamañoApodo {
            get {
                return ResourceManager.GetString("mensajeErrorTamañoApodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás en una casilla de tipo Entrada Gratis. ¡Disfrútala!.
        /// </summary>
        internal static string mensajeEstasEnCasillaTipoEntrada {
            get {
                return ResourceManager.GetString("mensajeEstasEnCasillaTipoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás en una casilla de tipo Fase Gratis. ¡Disfrútala!.
        /// </summary>
        internal static string mensajeEstasEnCasillaTipoFaseGratis {
            get {
                return ResourceManager.GetString("mensajeEstasEnCasillaTipoFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excepción recibiendo datos: .
        /// </summary>
        internal static string mensajeExcepcionRecibiendoDatos {
            get {
                return ResourceManager.GetString("mensajeExcepcionRecibiendoDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel ya tiene dueño y no es expropiable.
        /// </summary>
        internal static string mensajeExpropiacionImposible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres expropiar el hotel {0} al jugador {1}?.
        /// </summary>
        internal static string mensajeExpropiacionPosible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la compra del hotel {0}.
        /// </summary>
        internal static string mensajeFondosInsuficientesParaComprarHotel {
            get {
                return ResourceManager.GetString("mensajeFondosInsuficientesParaComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel {0} está completamente construido.
        /// </summary>
        internal static string mensajeHotelContruidoEntero {
            get {
                return ResourceManager.GetString("mensajeHotelContruidoEntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel {0} aun no tiene todas las fases hechas.
        /// </summary>
        internal static string mensajeHotelFasesIncompletas {
            get {
                return ResourceManager.GetString("mensajeHotelFasesIncompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel ha sido pagado. Subasta finalizada.
        /// </summary>
        internal static string mensajeHotelPagado {
            get {
                return ResourceManager.GetString("mensajeHotelPagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel vendido al jugador {0} ({1}) por {2}.
        /// </summary>
        internal static string mensajeHotelVendido {
            get {
                return ResourceManager.GetString("mensajeHotelVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado aun un idioma. Se usará por defecto el idioma del sistema operativo o inglés si no está soportado. Puede cambiarse en la ventana prinicipal del juego..
        /// </summary>
        internal static string mensajeIdiomaPorDefecto {
            get {
                return ResourceManager.GetString("mensajeIdiomaPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID no puede quedar en blanco.
        /// </summary>
        internal static string mensajeIDPartidaVacio {
            get {
                return ResourceManager.GetString("mensajeIDPartidaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya posees este hotel.
        /// </summary>
        internal static string mensajeImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("mensajeImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la partida:.
        /// </summary>
        internal static string mensajeInputNombrePartida {
            get {
                return ResourceManager.GetString("mensajeInputNombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de jugadores de la partida:.
        /// </summary>
        internal static string mensajeInputNumJugadoresPartida {
            get {
                return ResourceManager.GetString("mensajeInputNumJugadoresPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especifica una contraseña para evitar que cualquiera la cargue.
        /// </summary>
        internal static string mensajeInputPasswordPartida {
            get {
                return ResourceManager.GetString("mensajeInputPasswordPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha vendido el hotel que se estaba intentando ampliar, se anula la construcción..
        /// </summary>
        internal static string mensajeIntentarConstruirHotelVendido {
            get {
                return ResourceManager.GetString("mensajeIntentarConstruirHotelVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el ID de la partida salvada.
        /// </summary>
        internal static string mensajeIntroduceID {
            get {
                return ResourceManager.GetString("mensajeIntroduceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce la contraseña de la partida.
        /// </summary>
        internal static string mensajeIntroducePassword {
            get {
                return ResourceManager.GetString("mensajeIntroducePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error salvando el juego. Si el problema persiste, contacta con ifilgud@gmail.com por favor.
        /// </summary>
        internal static string mensajeJuegoNoSalvado {
            get {
                return ResourceManager.GetString("mensajeJuegoNoSalvado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego salvado correctamente por el usuario {0} con id {1} y contraseña &quot;{2}&quot;. Anota el id y la contraseña para poder cargarla en el futuro. Solo el creador podrá cargar la partida y solo los jugadores activos podrán unirse..
        /// </summary>
        internal static string mensajeJuegoSalvado {
            get {
                return ResourceManager.GetString("mensajeJuegoSalvado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0}.
        /// </summary>
        internal static string mensajeJugador {
            get {
                return ResourceManager.GetString("mensajeJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 1 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador1SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador1SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 2 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador2SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador2SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 3 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador3SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador3SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 4 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador4SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador4SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada porque todos los jugadores se han retirado.
        /// </summary>
        internal static string mensajeJugadoresRetidados {
            get {
                return ResourceManager.GetString("mensajeJugadoresRetidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) ha sido expulsado por hacer trampas.
        /// </summary>
        internal static string mensajeJugadorExpulsadoTrampas {
            get {
                return ResourceManager.GetString("mensajeJugadorExpulsadoTrampas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} ({1}) se ha retirado.
        /// </summary>
        internal static string mensajeJugadorRetirado {
            get {
                return ResourceManager.GetString("mensajeJugadorRetirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El error producido fue:.
        /// </summary>
        internal static string mensajeMostrarErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeMostrarErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string mensajeNo {
            get {
                return ResourceManager.GetString("mensajeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No conectado.
        /// </summary>
        internal static string mensajeNoConectado {
            get {
                return ResourceManager.GetString("mensajeNoConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviar un mensaje vacío.
        /// </summary>
        internal static string mensajeNoEnvMensajeVacio {
            get {
                return ResourceManager.GetString("mensajeNoEnvMensajeVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel {0} no tiene fases construídas y por tanto no se le pueden añadir entradas aun.
        /// </summary>
        internal static string mensajeNohayFasesConstruidasParaPonerEntradas {
            get {
                return ResourceManager.GetString("mensajeNohayFasesConstruidasParaPonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha indicado el dinero mínimo necesario.
        /// </summary>
        internal static string mensajeNoIndicadoDineroNecesario {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoDineroNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha indicado aun el número de jugadores.
        /// </summary>
        internal static string mensajeNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede dejar el nombre de la partida en blanco.
        /// </summary>
        internal static string mensajeNombrePartidaEnBlanco {
            get {
                return ResourceManager.GetString("mensajeNombrePartidaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la partida no puede contener el carácter &apos;~&apos;.
        /// </summary>
        internal static string mensajeNombrePartidaInvalido {
            get {
                return ResourceManager.GetString("mensajeNombrePartidaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la partida no puede contener más de 50 caracteres.
        /// </summary>
        internal static string mensajeNombrePartidaLargo {
            get {
                return ResourceManager.GetString("mensajeNombrePartidaLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una partida con ese nombre.
        /// </summary>
        internal static string mensajeNombrePartidaYaExiste {
            get {
                return ResourceManager.GetString("mensajeNombrePartidaYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes la versión más nueva :).
        /// </summary>
        internal static string mensajeNoNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNoNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posees ningún hotel.
        /// </summary>
        internal static string mensajeNoPoseesHoteles {
            get {
                return ResourceManager.GetString("mensajeNoPoseesHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha pujado todavía.
        /// </summary>
        internal static string mensajeNoPujadoTodavia {
            get {
                return ResourceManager.GetString("mensajeNoPujadoTodavia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} no ha podido cargarse por un error en el servidor. Contacte con ifilgud@gmail.com.
        /// </summary>
        internal static string mensajeNoSePuedeCargarErrorCargar {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarErrorCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} no ha sido cargado correctamente por un error en los datos salvados. Contacte con ifilgud@gmail.com.
        /// </summary>
        internal static string mensajeNoSePuedeCargarErrorDatos {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarErrorDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} no fue creado por ti.
        /// </summary>
        internal static string mensajeNoSePuedeCargarNoCreador {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarNoCreador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} no ha sido encontrado.
        /// </summary>
        internal static string mensajeNoSePuedeCargarNoExiste {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta para el juego con ID {0}.
        /// </summary>
        internal static string mensajeNoSePuedeCargarPasswordIncorrecta {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarPasswordIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} ya ha sido cargado por {1}.
        /// </summary>
        internal static string mensajeNoSePuedeCargarYaCargado {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarYaCargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego con ID {0} ya finalizó.
        /// </summary>
        internal static string mensajeNoSePuedeCargarYaFinalizada {
            get {
                return ResourceManager.GetString("mensajeNoSePuedeCargarYaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una versión diferente ({0}) que la que estás usando ({1}). ¿Quieres acceder a la página del proyecto en SourceForge? El juego se cerrará..
        /// </summary>
        internal static string mensajeNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de ampliaciones.
        /// </summary>
        internal static string mensajeNumAmpliaciones {
            get {
                return ResourceManager.GetString("mensajeNumAmpliaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de entradas: .
        /// </summary>
        internal static string mensajeNumEntradas {
            get {
                return ResourceManager.GetString("mensajeNumEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede dejar el número de jugadores en blanco.
        /// </summary>
        internal static string mensajeNumJugadoresEnBlanco {
            get {
                return ResourceManager.GetString("mensajeNumJugadoresEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número máximo de jugadores es 4.
        /// </summary>
        internal static string mensajeNumMaximoJugadores {
            get {
                return ResourceManager.GetString("mensajeNumMaximoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número mínimo de jugadores es 2.
        /// </summary>
        internal static string mensajeNumMinimoJugadores {
            get {
                return ResourceManager.GetString("mensajeNumMinimoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes pagar {0} por {1} noches en el {2} al jugador {3} ({4}).
        /// </summary>
        internal static string mensajePagarNoches {
            get {
                return ResourceManager.GetString("mensajePagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada. ¡Ha ganado el jugador {0}!.
        /// </summary>
        internal static string mensajePartidaFinalizada {
            get {
                return ResourceManager.GetString("mensajePartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida {0} está llena.
        /// </summary>
        internal static string mensajePartidaLlena {
            get {
                return ResourceManager.GetString("mensajePartidaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida {0} ya está empezada.
        /// </summary>
        internal static string mensajePartidaYaEmpezada {
            get {
                return ResourceManager.GetString("mensajePartidaYaEmpezada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida {0} ya está terminada.
        /// </summary>
        internal static string mensajePartidaYaTerminada {
            get {
                return ResourceManager.GetString("mensajePartidaYaTerminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede quedar en blanco.
        /// </summary>
        internal static string mensajePasswordVacia {
            get {
                return ResourceManager.GetString("mensajePasswordVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres que haya precio mínimo en la subasta?
        ///Se establecerá a un tercio del valor de compra del suelo más las ampliaciones construidas.
        /// </summary>
        internal static string mensajePrecioMinimoEnSubasta {
            get {
                return ResourceManager.GetString("mensajePrecioMinimoEnSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres jugar online?.
        /// </summary>
        internal static string mensajePreguntarSiOnline {
            get {
                return ResourceManager.GetString("mensajePreguntarSiOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La primera entrada que selecciones será la gratuíta debido a la casilla en la que estás. Las consecutivas serán según el método normal (una por hotel).
        /// </summary>
        internal static string mensajePrimeraEntradaGratis {
            get {
                return ResourceManager.GetString("mensajePrimeraEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un problema de conexión con el servidor.
        /// </summary>
        internal static string mensajeProblemaConexionConServidor {
            get {
                return ResourceManager.GetString("mensajeProblemaConexionConServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres reiniciar la partida?.
        /// </summary>
        internal static string mensajeReiniciarPartida {
            get {
                return ResourceManager.GetString("mensajeReiniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres retirarte?.
        /// </summary>
        internal static string mensajeRetirarse {
            get {
                return ResourceManager.GetString("mensajeRetirarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Has sacado un 6. Puedes volver a tirar!.
        /// </summary>
        internal static string mensajeSacadoUnSeis {
            get {
                return ResourceManager.GetString("mensajeSacadoUnSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se puede salvar antes de tirar el dado.
        /// </summary>
        internal static string mensajeSalvarAntesDeTirar {
            get {
                return ResourceManager.GetString("mensajeSalvarAntesDeTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has de seleccionar al menos un usuario sin incluir el tuyo.
        /// </summary>
        internal static string mensajeSeleccionarUsuarios {
            get {
                return ResourceManager.GetString("mensajeSeleccionarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el nº de jugadores.
        /// </summary>
        internal static string mensajeSelecJugadores {
            get {
                return ResourceManager.GetString("mensajeSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        internal static string mensajeSi {
            get {
                return ResourceManager.GetString("mensajeSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 100.
        /// </summary>
        internal static string mensajeSinBilletesDe100 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 1000.
        /// </summary>
        internal static string mensajeSinBilletesDe1000 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 50.
        /// </summary>
        internal static string mensajeSinBilletesDe50 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 500.
        /// </summary>
        internal static string mensajeSinBilletesDe500 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 5000.
        /// </summary>
        internal static string mensajeSinBilletesDe5000 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el dinero suficiente para comprar.
        /// </summary>
        internal static string mensajeSinDineroParaComprar {
            get {
                return ResourceManager.GetString("mensajeSinDineroParaComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes dinero suficiente para pagar una entrada del hotel .
        /// </summary>
        internal static string mensajeSinDineroParaComprarEntradas {
            get {
                return ResourceManager.GetString("mensajeSinDineroParaComprarEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la expropiación.
        /// </summary>
        internal static string mensajeSinFondosParaExpropiacion {
            get {
                return ResourceManager.GetString("mensajeSinFondosParaExpropiacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes propiedades para subastar ni fondos suficientes para pagar. Quedas eliminado de la partida :(.
        /// </summary>
        internal static string mensajeSinPropiedadesNiFondos {
            get {
                return ResourceManager.GetString("mensajeSinPropiedadesNiFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes propiedades para subastar.
        /// </summary>
        internal static string mensajeSinPropiedadesParaSubastar {
            get {
                return ResourceManager.GetString("mensajeSinPropiedadesParaSubastar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelo comprado: .
        /// </summary>
        internal static string mensajeSueloComprado {
            get {
                return ResourceManager.GetString("mensajeSueloComprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes dinero suficiente para pagar {0}  
        ///Si decides continuar, el resultado del dado ha de ser cumplido obligatoriamente.
        ///¿Deseas tirar el dado?.
        /// </summary>
        internal static string mensajeSuficienteDineroParaFase {
            get {
                return ResourceManager.GetString("mensajeSuficienteDineroParaFase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes dinero suficiente para pagar los complejos recreativos.
        ///No se necesita el permiso para construirlos. ¿Deseas continuar?.
        /// </summary>
        internal static string mensajeSufucienteDineroParaComplejos {
            get {
                return ResourceManager.GetString("mensajeSufucienteDineroParaComplejos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviar un mensaje de más de 1024 caracteres.
        /// </summary>
        internal static string mensajeTamMensajeMax {
            get {
                return ResourceManager.GetString("mensajeTamMensajeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sacado un {0}, por lo que el jugador {1} debe abonar {2} al jugador {3}.
        /// </summary>
        internal static string mensajeTotalAPagar {
            get {
                return ResourceManager.GetString("mensajeTotalAPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} quiere que te unas a un chat privado. ¿Deseas hacerlo?.
        /// </summary>
        internal static string mensajeUnirseAChat {
            get {
                return ResourceManager.GetString("mensajeUnirseAChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La versión del juego que estás ejecutando no es compatible con el servidor al que has conectado. Necesitas la versión {0}.
        /// </summary>
        internal static string mensajeVersionNoActualizada {
            get {
                return ResourceManager.GetString("mensajeVersionNoActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás dentro de la partida .
        /// </summary>
        internal static string mensajeYaDentroPartida {
            get {
                return ResourceManager.GetString("mensajeYaDentroPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a J.
        /// </summary>
        internal static string textoAbreviaturaJugador {
            get {
                return ResourceManager.GetString("textoAbreviaturaJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a los complejos recreativos.
        /// </summary>
        internal static string textoComplejosRecreativos {
            get {
                return ResourceManager.GetString("textoComplejosRecreativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la cuarta ampliación.
        /// </summary>
        internal static string textoCuartaAmpliacion {
            get {
                return ResourceManager.GetString("textoCuartaAmpliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a el edificio principal.
        /// </summary>
        internal static string textoEdificioPrincipal {
            get {
                return ResourceManager.GetString("textoEdificioPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargada.
        /// </summary>
        internal static string textoEstadoCargada {
            get {
                return ResourceManager.GetString("textoEstadoCargada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        internal static string textoEstadoDisponible {
            get {
                return ResourceManager.GetString("textoEstadoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezada.
        /// </summary>
        internal static string textoEstadoEmpezada {
            get {
                return ResourceManager.GetString("textoEstadoEmpezada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizada.
        /// </summary>
        internal static string textoEstadoFinalizada {
            get {
                return ResourceManager.GetString("textoEstadoFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llena.
        /// </summary>
        internal static string textoEstadoLlena {
            get {
                return ResourceManager.GetString("textoEstadoLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesario: .
        /// </summary>
        internal static string textoNecesario {
            get {
                return ResourceManager.GetString("textoNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ({1} jugadores de {2}). Estado: {3}.
        /// </summary>
        internal static string textoPartidaPlural {
            get {
                return ResourceManager.GetString("textoPartidaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} (1 jugador de {1}). Estado: {2}.
        /// </summary>
        internal static string textoPartidaSingular {
            get {
                return ResourceManager.GetString("textoPartidaSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la primera ampliación.
        /// </summary>
        internal static string textoPrimeraAmpliacion {
            get {
                return ResourceManager.GetString("textoPrimeraAmpliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la segunda ampliación.
        /// </summary>
        internal static string textoSegundaAmpliacion {
            get {
                return ResourceManager.GetString("textoSegundaAmpliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la tercera ampliación.
        /// </summary>
        internal static string textoTerceraAmpliacion {
            get {
                return ResourceManager.GetString("textoTerceraAmpliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes: .
        /// </summary>
        internal static string textoTienes {
            get {
                return ResourceManager.GetString("textoTienes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        internal static string textoTotal {
            get {
                return ResourceManager.GetString("textoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usas: .
        /// </summary>
        internal static string textoUsas {
            get {
                return ResourceManager.GetString("textoUsas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string TipoCasillaComprar {
            get {
                return ResourceManager.GetString("TipoCasillaComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construir.
        /// </summary>
        internal static string TipoCasillaConstruir {
            get {
                return ResourceManager.GetString("TipoCasillaConstruir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada gratis.
        /// </summary>
        internal static string TipoCasillaEntradaGratis {
            get {
                return ResourceManager.GetString("TipoCasillaEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fase gratis.
        /// </summary>
        internal static string TipoCasillaFaseGratis {
            get {
                return ResourceManager.GetString("TipoCasillaFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida.
        /// </summary>
        internal static string TipoCasillaSalida {
            get {
                return ResourceManager.GetString("TipoCasillaSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a Hotel!.
        /// </summary>
        internal static string tituloBienvenido {
            get {
                return ResourceManager.GetString("tituloBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar partida.
        /// </summary>
        internal static string tituloCargarPartida {
            get {
                return ResourceManager.GetString("tituloCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar entrada.
        /// </summary>
        internal static string tituloComprarEntrada {
            get {
                return ResourceManager.GetString("tituloComprarEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar hotel.
        /// </summary>
        internal static string tituloComprarHotel {
            get {
                return ResourceManager.GetString("tituloComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de construcción.
        /// </summary>
        internal static string tituloConfirmacionDeConstruccion {
            get {
                return ResourceManager.GetString("tituloConfirmacionDeConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación para desconectar.
        /// </summary>
        internal static string tituloConfirmacionDesconectar {
            get {
                return ResourceManager.GetString("tituloConfirmacionDesconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de inicio de subasta.
        /// </summary>
        internal static string tituloConfirmacionSubasta {
            get {
                return ResourceManager.GetString("tituloConfirmacionSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de puja.
        /// </summary>
        internal static string tituloConfirmarPuja {
            get {
                return ResourceManager.GetString("tituloConfirmarPuja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de venta.
        /// </summary>
        internal static string tituloConfirmarVentaSubasta {
            get {
                return ResourceManager.GetString("tituloConfirmarVentaSubasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción cancelada.
        /// </summary>
        internal static string tituloConstruccionCancelada {
            get {
                return ResourceManager.GetString("tituloConstruccionCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        internal static string tituloCrearPartida {
            get {
                return ResourceManager.GetString("tituloCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar una partida.
        /// </summary>
        internal static string tituloDialogoCargarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar una partida.
        /// </summary>
        internal static string tituloDialogoGuardarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero insuficiente.
        /// </summary>
        internal static string tituloDineroInsuficiente {
            get {
                return ResourceManager.GetString("tituloDineroInsuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string tituloError {
            get {
                return ResourceManager.GetString("tituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El error producido fue:.
        /// </summary>
        internal static string tituloErrorAlComprobarVersion {
            get {
                return ResourceManager.GetString("tituloErrorAlComprobarVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación imposible.
        /// </summary>
        internal static string tituloExpropiacionImposible {
            get {
                return ResourceManager.GetString("tituloExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación posible.
        /// </summary>
        internal static string tituloExpropiacionPosible {
            get {
                return ResourceManager.GetString("tituloExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotel.
        /// </summary>
        internal static string tituloHotel {
            get {
                return ResourceManager.GetString("tituloHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible realizar la compra.
        /// </summary>
        internal static string tituloImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("tituloImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imposible incrementar.
        /// </summary>
        internal static string tituloImposibleIncrementar {
            get {
                return ResourceManager.GetString("tituloImposibleIncrementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador eliminado.
        /// </summary>
        internal static string tituloJugadorEliminado {
            get {
                return ResourceManager.GetString("tituloJugadorEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible construir.
        /// </summary>
        internal static string tituloNoEsPosibleConstruir {
            get {
                return ResourceManager.GetString("tituloNoEsPosibleConstruir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible mostrar tus hoteles.
        /// </summary>
        internal static string tituloNoEsPosibleMostrarTusHoteles {
            get {
                return ResourceManager.GetString("tituloNoEsPosibleMostrarTusHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible poner entradas.
        /// </summary>
        internal static string tituloNoesPosiblePonerEntradas {
            get {
                return ResourceManager.GetString("tituloNoesPosiblePonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de colores.
        /// </summary>
        internal static string tituloNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("tituloNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede comprar el suelo.
        /// </summary>
        internal static string tituloNoSePuedeComparSuelo {
            get {
                return ResourceManager.GetString("tituloNoSePuedeComparSuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo chat.
        /// </summary>
        internal static string tituloNuevoChat {
            get {
                return ResourceManager.GetString("tituloNuevoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar noches.
        /// </summary>
        internal static string tituloPagarNoches {
            get {
                return ResourceManager.GetString("tituloPagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible iniciar.
        /// </summary>
        internal static string tituloSelecJugadores {
            get {
                return ResourceManager.GetString("tituloSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subastas.
        /// </summary>
        internal static string tituloSubastas {
            get {
                return ResourceManager.GetString("tituloSubastas", resourceCulture);
            }
        }
    }
}
