//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.261
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juego_Hotel.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juego_Hotel.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string comboBoxIdiomas1 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string comboBoxIdiomas2 {
            get {
                return ResourceManager.GetString("comboBoxIdiomas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida de Hotel|*.xml.
        /// </summary>
        internal static string filtroDialogoCargarGuardarPartida {
            get {
                return ResourceManager.GetString("filtroDialogoCargarGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres comprobar si existe una versión del juego más actualizada?.
        /// </summary>
        internal static string mensajeActualizar {
            get {
                return ResourceManager.GetString("mensajeActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida actual se perderá si continúas, tanto si la carga es exitosa como no, ¿Quieres proceder?.
        /// </summary>
        internal static string mensajeCargarPartida {
            get {
                return ResourceManager.GetString("mensajeCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Entrada Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaEntradaGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has caído en una casilla de tipo Fase Gratis, ¡aprovecha!.
        /// </summary>
        internal static string mensajeCasillaFaseGratis {
            get {
                return ResourceManager.GetString("mensajeCasillaFaseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casilla está ocupada y no puedes añadir una entrada ahora mismo en ella.
        /// </summary>
        internal static string mensajeCasillaOcupada {
            get {
                return ResourceManager.GetString("mensajeCasillaOcupada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casilla ya tiene una entrada comprada para el hotel .
        /// </summary>
        internal static string mensajeCasillaYaPoseeEntrada {
            get {
                return ResourceManager.GetString("mensajeCasillaYaPoseeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si aceptas comprar la entrada, estás obligado a pagarla. ¿Deseas realizar la compra?.
        /// </summary>
        internal static string mensajeComprarEntradas {
            get {
                return ResourceManager.GetString("mensajeComprarEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes comprar el hotel. Si decides continuar, estás obligado a pagarlo. ¿Deseas realizar la compra?.
        /// </summary>
        internal static string mensajeComprarHotel {
            get {
                return ResourceManager.GetString("mensajeComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción denegada.
        /// </summary>
        internal static string mensajeConstruccionDenegada {
            get {
                return ResourceManager.GetString("mensajeConstruccionDenegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción de coste doble.
        /// </summary>
        internal static string mensajeConstruccionDobleCoste {
            get {
                return ResourceManager.GetString("mensajeConstruccionDobleCoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción gratuita.
        /// </summary>
        internal static string mensajeConstruccionGratuita {
            get {
                return ResourceManager.GetString("mensajeConstruccionGratuita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción permitida.
        /// </summary>
        internal static string mensajeConstruccionPermitida {
            get {
                return ResourceManager.GetString("mensajeConstruccionPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a construidas: .
        /// </summary>
        internal static string mensajeConstruidas {
            get {
                return ResourceManager.GetString("mensajeConstruidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador {0} debe pagar las noches al jugador {1}. Pulsa OK para lanzar el dado..
        /// </summary>
        internal static string mensajeDebePagarNoches {
            get {
                return ResourceManager.GetString("mensajeDebePagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dueño: .
        /// </summary>
        internal static string mensajeDuenio {
            get {
                return ResourceManager.GetString("mensajeDuenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error comprobando la versión. Ve a https://sourceforge.net/projects/hotels-game/ para comprobar la versión manualmente..
        /// </summary>
        internal static string mensajeErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlCargar {
            get {
                return ResourceManager.GetString("mensajeErrorAlCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error salvando la partida: {0}.
        /// </summary>
        internal static string mensajeErrorAlSalvar {
            get {
                return ResourceManager.GetString("mensajeErrorAlSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar el fichero de configuración Config.xml.
        /// </summary>
        internal static string mensajeErrorCargarConfig {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cargar la configuración desde el servidor.
        /// </summary>
        internal static string mensajeErrorCargarConfigServidor {
            get {
                return ResourceManager.GetString("mensajeErrorCargarConfigServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás en una casilla de tipo Entrada Gratis. ¡Disfrútala!.
        /// </summary>
        internal static string mensajeEstasEnCasillaTipoEntrada {
            get {
                return ResourceManager.GetString("mensajeEstasEnCasillaTipoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel ya tiene dueño y no es expropiable.
        /// </summary>
        internal static string mensajeExpropiacionImposible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres expropiar el hotel {0} al jugador {1}?.
        /// </summary>
        internal static string mensajeExpropiacionPosible {
            get {
                return ResourceManager.GetString("mensajeExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la compra del hotel {0}.
        /// </summary>
        internal static string mensajeFondosInsuficientesParaComprarHotel {
            get {
                return ResourceManager.GetString("mensajeFondosInsuficientesParaComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya posees este hotel.
        /// </summary>
        internal static string mensajeImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("mensajeImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha vendido el hotel que se estaba intentando ampliar, se anula la construcción..
        /// </summary>
        internal static string mensajeIntentarConstruirHotelVendido {
            get {
                return ResourceManager.GetString("mensajeIntentarConstruirHotelVendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador .
        /// </summary>
        internal static string mensajeJugador {
            get {
                return ResourceManager.GetString("mensajeJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 1 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador1SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador1SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 2 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador2SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador2SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 3 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador3SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador3SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador 4 no tiene color asociado.
        /// </summary>
        internal static string mensajeJugador4SinColor {
            get {
                return ResourceManager.GetString("mensajeJugador4SinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada porque todos los jugadores se han retirado.
        /// </summary>
        internal static string mensajeJugadoresRetidados {
            get {
                return ResourceManager.GetString("mensajeJugadoresRetidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El error producido fue:.
        /// </summary>
        internal static string mensajeMostrarErrorActualizador {
            get {
                return ResourceManager.GetString("mensajeMostrarErrorActualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string mensajeNo {
            get {
                return ResourceManager.GetString("mensajeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El hotel {0} no tiene fases construídas y por tanto no se le pueden añadir entradas aun.
        /// </summary>
        internal static string mensajeNohayFasesConstruidasParaPonerEntradas {
            get {
                return ResourceManager.GetString("mensajeNohayFasesConstruidasParaPonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha indicado el dinero mínimo necesario.
        /// </summary>
        internal static string mensajeNoIndicadoDineroNecesario {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoDineroNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha indicado aun el número de jugadores.
        /// </summary>
        internal static string mensajeNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("mensajeNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes la versión más nueva :).
        /// </summary>
        internal static string mensajeNoNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNoNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posees ningún hotel.
        /// </summary>
        internal static string mensajeNoPoseesHoteles {
            get {
                return ResourceManager.GetString("mensajeNoPoseesHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe una versión diferente ({0}) que la que estás usando ({1}). ¿Quieres acceder a la página del proyecto en SourceForge? El juego se cerrará..
        /// </summary>
        internal static string mensajeNuevaVersion {
            get {
                return ResourceManager.GetString("mensajeNuevaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de ampliaciones.
        /// </summary>
        internal static string mensajeNumAmpliaciones {
            get {
                return ResourceManager.GetString("mensajeNumAmpliaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de entradas: .
        /// </summary>
        internal static string mensajeNumEntradas {
            get {
                return ResourceManager.GetString("mensajeNumEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada. ¡Ha ganado el jugador {0}!.
        /// </summary>
        internal static string mensajePartidaFinalizada {
            get {
                return ResourceManager.GetString("mensajePartidaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres jugar online?.
        /// </summary>
        internal static string mensajePreguntarSiOnline {
            get {
                return ResourceManager.GetString("mensajePreguntarSiOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La primera entrada que selecciones será la gratuíta debido a la casilla en la que estás. Las consecutivas serán según el método normal (una por hotel).
        /// </summary>
        internal static string mensajePrimeraEntradaGratis {
            get {
                return ResourceManager.GetString("mensajePrimeraEntradaGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres reiniciar la partida?.
        /// </summary>
        internal static string mensajeReiniciarPartida {
            get {
                return ResourceManager.GetString("mensajeReiniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres retirarte?.
        /// </summary>
        internal static string mensajeRetirarse {
            get {
                return ResourceManager.GetString("mensajeRetirarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Has sacado un 6. Puedes volver a tirar!.
        /// </summary>
        internal static string mensajeSacadoUnSeis {
            get {
                return ResourceManager.GetString("mensajeSacadoUnSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se puede salvar antes de tirar el dado.
        /// </summary>
        internal static string mensajeSalvarAntesDeTirar {
            get {
                return ResourceManager.GetString("mensajeSalvarAntesDeTirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el nº de jugadores.
        /// </summary>
        internal static string mensajeSelecJugadores {
            get {
                return ResourceManager.GetString("mensajeSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí.
        /// </summary>
        internal static string mensajeSi {
            get {
                return ResourceManager.GetString("mensajeSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 100.
        /// </summary>
        internal static string mensajeSinBilletesDe100 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 1000.
        /// </summary>
        internal static string mensajeSinBilletesDe1000 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 50.
        /// </summary>
        internal static string mensajeSinBilletesDe50 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 500.
        /// </summary>
        internal static string mensajeSinBilletesDe500 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes tantos billetes de 5000.
        /// </summary>
        internal static string mensajeSinBilletesDe5000 {
            get {
                return ResourceManager.GetString("mensajeSinBilletesDe5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes dinero suficiente para pagar una entrada del hotel .
        /// </summary>
        internal static string mensajeSinDineroParaComprarEntradas {
            get {
                return ResourceManager.GetString("mensajeSinDineroParaComprarEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes fondos para realizar la expropiación.
        /// </summary>
        internal static string mensajeSinFondosParaExpropiacion {
            get {
                return ResourceManager.GetString("mensajeSinFondosParaExpropiacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes propiedades para subastar ni fondos suficientes para pagar. Quedas eliminado de la partida :(.
        /// </summary>
        internal static string mensajeSinPropiedadesNiFondos {
            get {
                return ResourceManager.GetString("mensajeSinPropiedadesNiFondos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes propiedades para subastar.
        /// </summary>
        internal static string mensajeSinPropiedadesParaSubastar {
            get {
                return ResourceManager.GetString("mensajeSinPropiedadesParaSubastar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suelo comprado: .
        /// </summary>
        internal static string mensajeSueloComprado {
            get {
                return ResourceManager.GetString("mensajeSueloComprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sacado un {0}, por lo que el jugador {1} debe abonar {2} al jugador {3}.
        /// </summary>
        internal static string mensajeTotalAPagar {
            get {
                return ResourceManager.GetString("mensajeTotalAPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesario: .
        /// </summary>
        internal static string textoNecesario {
            get {
                return ResourceManager.GetString("textoNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes: .
        /// </summary>
        internal static string textoTienes {
            get {
                return ResourceManager.GetString("textoTienes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        internal static string textoTotal {
            get {
                return ResourceManager.GetString("textoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usas: .
        /// </summary>
        internal static string textoUsas {
            get {
                return ResourceManager.GetString("textoUsas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido a Hotel!.
        /// </summary>
        internal static string tituloBienvenido {
            get {
                return ResourceManager.GetString("tituloBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar partida.
        /// </summary>
        internal static string tituloCargarPartida {
            get {
                return ResourceManager.GetString("tituloCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar entrada.
        /// </summary>
        internal static string tituloComprarEntrada {
            get {
                return ResourceManager.GetString("tituloComprarEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar hotel.
        /// </summary>
        internal static string tituloComprarHotel {
            get {
                return ResourceManager.GetString("tituloComprarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Construcción cancelada.
        /// </summary>
        internal static string tituloConstruccionCancelada {
            get {
                return ResourceManager.GetString("tituloConstruccionCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar una partida.
        /// </summary>
        internal static string tituloDialogoCargarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoCargarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar una partida.
        /// </summary>
        internal static string tituloDialogoGuardarPartida {
            get {
                return ResourceManager.GetString("tituloDialogoGuardarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero insuficiente.
        /// </summary>
        internal static string tituloDineroInsuficiente {
            get {
                return ResourceManager.GetString("tituloDineroInsuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string tituloError {
            get {
                return ResourceManager.GetString("tituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación imposible.
        /// </summary>
        internal static string tituloExpropiacionImposible {
            get {
                return ResourceManager.GetString("tituloExpropiacionImposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expropriación posible.
        /// </summary>
        internal static string tituloExpropiacionPosible {
            get {
                return ResourceManager.GetString("tituloExpropiacionPosible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotels.
        /// </summary>
        internal static string tituloHotel {
            get {
                return ResourceManager.GetString("tituloHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible realizar la compra.
        /// </summary>
        internal static string tituloImposibleComprarHotelTuyo {
            get {
                return ResourceManager.GetString("tituloImposibleComprarHotelTuyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imposible incrementar.
        /// </summary>
        internal static string tituloImposibleIncrementar {
            get {
                return ResourceManager.GetString("tituloImposibleIncrementar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador eliminado.
        /// </summary>
        internal static string tituloJugadorEliminado {
            get {
                return ResourceManager.GetString("tituloJugadorEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible mostrar tus hoteles.
        /// </summary>
        internal static string tituloNoEsPosibleMostrarTusHoteles {
            get {
                return ResourceManager.GetString("tituloNoEsPosibleMostrarTusHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible poner entradas.
        /// </summary>
        internal static string tituloNoesPosiblePonerEntradas {
            get {
                return ResourceManager.GetString("tituloNoesPosiblePonerEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de colores.
        /// </summary>
        internal static string tituloNoIndicadoJugadores {
            get {
                return ResourceManager.GetString("tituloNoIndicadoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar noches.
        /// </summary>
        internal static string tituloPagarNoches {
            get {
                return ResourceManager.GetString("tituloPagarNoches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible iniciar.
        /// </summary>
        internal static string tituloSelecJugadores {
            get {
                return ResourceManager.GetString("tituloSelecJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subastas.
        /// </summary>
        internal static string tituloSubastas {
            get {
                return ResourceManager.GetString("tituloSubastas", resourceCulture);
            }
        }
    }
}
