//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juego_Hotel.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juego_Hotel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Billete_100 {
            get {
                object obj = ResourceManager.GetObject("Billete_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billete_1000 {
            get {
                object obj = ResourceManager.GetObject("Billete_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billete_50 {
            get {
                object obj = ResourceManager.GetObject("Billete_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billete_500 {
            get {
                object obj = ResourceManager.GetObject("Billete_500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Billete_5000 {
            get {
                object obj = ResourceManager.GetObject("Billete_5000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Boomerang_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Boomerang_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;config&gt;
        ///   &lt;money_per_player&gt;
        ///      &lt;two_players&gt;
        ///         &lt;n_5000&gt;2&lt;/n_5000&gt;
        ///         &lt;n_1000&gt;11&lt;/n_1000&gt;
        ///         &lt;n_500&gt;6&lt;/n_500&gt;
        ///         &lt;n_100&gt;8&lt;/n_100&gt;
        ///         &lt;n_50&gt;4&lt;/n_50&gt;
        ///      &lt;/two_players&gt;
        ///      &lt;three_or_four_players&gt;
        ///         &lt;n_5000&gt;1&lt;/n_5000&gt;
        ///         &lt;n_1000&gt;5&lt;/n_1000&gt;
        ///         &lt;n_500&gt;3&lt;/n_500&gt;
        ///         &lt;n_100&gt;4&lt;/n_100&gt;
        ///         &lt;n_50&gt;2&lt;/n_50&gt;
        ///      &lt;/three_or_four_players&gt;
        ///   &lt;/money_per_player&gt;
        ///&lt;/config&gt;.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Entrada {
            get {
                object obj = ResourceManager.GetObject("Entrada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flecha_amarilla {
            get {
                object obj = ResourceManager.GetObject("Flecha_amarilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flecha_azul {
            get {
                object obj = ResourceManager.GetObject("Flecha_azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flecha_roja {
            get {
                object obj = ResourceManager.GetObject("Flecha_roja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flecha_verde {
            get {
                object obj = ResourceManager.GetObject("Flecha_verde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fujiyama_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Fujiyama_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap green_tick {
            get {
                object obj = ResourceManager.GetObject("green-tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icono {
            get {
                object obj = ResourceManager.GetObject("Icono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Letoile_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Letoile_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap President_tarjeta {
            get {
                object obj = ResourceManager.GetObject("President_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reglas {
            get {
                object obj = ResourceManager.GetObject("Reglas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Royal_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Royal_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Safari_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Safari_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tablero {
            get {
                object obj = ResourceManager.GetObject("Tablero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Taj_Mahal_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Taj_Mahal_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Waikiki_tarjeta {
            get {
                object obj = ResourceManager.GetObject("Waikiki_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
